package upside.server;

import java.io.OutputStream;
import java.util.Map;

import upside.site.Category;
import upside.site.Feature;
import upside.site.Site;
import upside.utils.HtmlBuilder;

public class SiteIndexHandler extends PageHandler {

    private String siteName;

    public SiteIndexHandler(OutputStream out, String siteName) {
        super(out);
        this.siteName = siteName;
    }

    @Override
    public void handle() {
        Site merged = getSite(siteName);

        HtmlBuilder html = new HtmlBuilder();
        html.html();
        html.head();
        html.title("Upside - The update site federator - " + siteName);
        html.close();
        html.body();
        String url = merged.getDescription().getUrl();
        html.text(
            "This is an update site for Eclipse, generated by " +
            "<a href=\"http://github.com/torkjel/upside\">Upside</a> - The update site federator" +
            "<p>" +
            "Name: " + siteName + "<br>" +
            "URL: <a href=\"" + url + "\">" + url + "</a><br>" +
            "Description: " + merged.getDescription().getDescription() + "" +
            "<p>" +
            "This site includes plugins from the following update sites:");
        html.ul();
        Map<String, Site> sites = fm().getOriginSites(siteName);
        for (String name : sites.keySet()) {
            Site site = sites.get(name);
            html.li("<a href=\"" + site.getDescription().getUrl() + "\">" + name + "</a>" +
                    "<br>" +
                    "<i>" + site.getDescription().getDescription() + "</i>");
        }
        html.close();

        html.text("Add this update site (<b>" + url + "</b>) to your Eclipse installation to install the following plugins:");

        html.ul();
        for (Category category : merged.getCategories()) {
            html.li(category.getLabel());
            html.ul();
            for (Feature f : merged.getFeaturesIn(category))
                html.li(f.getId() + "/" + f.getVersion());
            html.close();
        }
        html.close();

        html.ul();
        for (Feature f : merged.getFeaturesWithoutCategory())
            html.li(f.getId() + "/" + f.getVersion());
        html.close();

        // TODO: Something odd here... An extra <ul/> in the generated html!?!

        html.text("<a href=\"" + url + Site.SITEXML + "\">site.xml</a>");

        html.close();
        html.close();

        write(html.toString());
    }

}
